#用print打印一个数据类型
print(type(0.666))
print(type("string"))
print(type(6))
#使用变量存储type输出的数据结构类型
int_type=type(6)
str_type=type("string")
float_type=type(0.66)
print(int_type)
print(str_type)
print(float_type)
#查看变量内存储的数据类型
i=6
s="string"
f=0.66
print(type(i))
print(type(s))
print(type(f))
