"""学习list等数据容器的使用"""
stu_name=["马加爵","董存瑞","马保国"]
print(stu_name)
print(type(stu_name))
stu=["马加爵",18,True]
print(stu)
#嵌套链表
li_list=[[123,12,1],[321,32,3]]
print(li_list)
print(stu_name[0])
print(stu_name[1])
#如果表示从右向左，从-1开始，依次递减
print(stu_name[-1])
#list的方法
#1，查询下标值，index
print(stu_name.index("董存瑞"))
#2，对指定下标位置的值修改
stu_name[1]="唐继尧"
print(stu_name[1])
#插入，
stu_name.insert(1,"熊庆来")
print(stu_name)
#追加元素
stu_name.append("方精云")
print(stu_name)
#追加一个新list
stu_name2=["冯友兰","华罗庚","傅聪"]
stu_name.extend(stu_name2)
print(stu_name)
#删除元素
del stu_name[0]
print(stu_name)
name= stu_name.pop(2)
print(f"{stu_name},通过pop取出元素{name}")
#移除第一个指定值的元素
stu_name3=["方精云","唐继尧","方精云"]
stu_name3.remove("方精云")
print(stu_name3)
#清空列表
stu_name3.clear()
print(stu_name3)
#统计指定元素在列表中的数量
stu_name4=["方精云","方精云","方精云","方精云","方精云","唐继尧","唐继尧"]
print(stu_name4.count("方精云"))
print(len(stu_name4))